const options = {
  headingLevelOptions: {
    h1: "h1",
    h2: "h2",
    h3: "h3",
    h4: "h4",
    h5: "h5",
    h6: "h6",
  },
  headingSizeOptions: {
    small: "small",
    medium: "medium",
    large: "large",
    xl: "xl",
  },
  textSizeOptions: {
    xs: "xs",
    small: "small",
    medium: "medium",
    large: "large",
    xl: "xl",
  },
  variantOptions: {
    primary: "primary",
    secondary: "secondary",
    success: "success",
    info: "info",
    warning: "warning",
    danger: "danger",
    "light-1": "light-1",
    "light-2": "light-2",
    "light-3": "light-3",
    "light-4": "light-4",
    "light-5": "light-5",
    "dark-1": "dark-1",
    "dark-2": "dark-2",
    "dark-3": "dark-3",
    white: "white",
    null: null,
  },
  colorOptions: {
    primary: "--rds-primary",
    secondary: "--rds-secondary",
    success: "--rds-success",
    info: "--rds-info",
    warning: "--rds-warning",
    danger: "--rds-danger",
    "light-1": "--rds-light-1",
    "light-2": "--rds-light-2",
    "light-3": "--rds-light-3",
    "light-4": "--rds-light-4",
    "light-5": "--rds-light-5",
    "dark-1": "--rds-dark-1",
    "dark-2": "--rds-dark-2",
    "dark-3": "--rds-dark-3",
    white: "--rds-white",
    null: null,
  },
  alignOptions: {
    left: "left",
    center: "center",
    right: "right",
  },
  screenOptions: {
    md: 768,
    lg: 992,
    xl: 1200,
  },
  fontWeightOptions: {
    bold: "bold",
    bolder: "bolder",
    semibold: "semibold",
    medium: "medium",
    normal: "normal",
    light: "light",
    lighter: "lighter",
  },
  tabActiveVariants: {
    primary: "rds-primary",
    secondary: "rds-secondary",
  },
  linkTargetOptions: {
    _blank: "_blank",
    _self: "_self",
    _parent: "_parent",
    _top: "_top",
  },
  spacingOptions: {
    0: "0",
    xxxs: "xxxs",
    xxs: "xxs",
    xs: "xs",
    sm: "sm",
    md: "md",
    lg: "lg",
    xl: "xl",
    xxl: "xxl",
    xxxl: "xxxl",
  },
};
export default options;
